global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'server-monitoring'
    metrics_path: /metrics
    static_configs:
      # Для Windows/WSL используем host.docker.internal; при Linux замените на 172.17.0.1
      - targets: ['host.docker.internal:8015']